function returnStateJSON(){

var stateJSON = {
"AZ": { "fillKey": "defaultFill" },
"CO": { "fillKey": "defaultFill" },
"DE": { "fillKey": "defaultFill" },
"FL": { "fillKey": "defaultFill" },
"GA": { "fillKey": "defaultFill" },
"HI": { "fillKey": "defaultFill" },
"ID": { "fillKey": "defaultFill" },
"IL": { "fillKey": "defaultFill" },
"IN": { "fillKey": "defaultFill" },
"IA": { "fillKey": "defaultFill" },
"KS": { "fillKey": "defaultFill" },
"KY": { "fillKey": "defaultFill" },
"LA": { "fillKey": "defaultFill" },
"MD": { "fillKey": "defaultFill" },
"ME": { "fillKey": "defaultFill" },
"MA": { "fillKey": "defaultFill" },
"MN": { "fillKey": "defaultFill" },
"MI": { "fillKey": "defaultFill" },
"MS": { "fillKey": "defaultFill" },
"MO": { "fillKey": "defaultFill" },
"MT": { "fillKey": "defaultFill" },
"NC": { "fillKey": "defaultFill" },
"NE": { "fillKey": "defaultFill" },
"NV": { "fillKey": "defaultFill" },
"NH": { "fillKey": "defaultFill" },
"NJ": { "fillKey": "defaultFill" },
"NY": { "fillKey": "defaultFill" },
"ND": { "fillKey": "defaultFill" },
"NM": { "fillKey": "defaultFill" },
"OH": { "fillKey": "defaultFill" },
"OK": { "fillKey": "defaultFill" },
"OR": { "fillKey": "defaultFill" },
"PA": { "fillKey": "defaultFill" },
"RI": { "fillKey": "defaultFill" },
"SC": { "fillKey": "defaultFill" },
"SD": { "fillKey": "defaultFill" },
"TN": { "fillKey": "defaultFill" },
"TX": { "fillKey": "defaultFill" },
"UT": { "fillKey": "defaultFill" },
"WI": { "fillKey": "defaultFill" },
"VA": { "fillKey": "defaultFill" },
"VT": { "fillKey": "defaultFill" },
"WA": { "fillKey": "defaultFill" },
"WV": { "fillKey": "defaultFill" },
"WY": { "fillKey": "defaultFill" },
"CA": { "fillKey": "defaultFill" },
"CT": { "fillKey": "defaultFill" },
"AK": { "fillKey": "defaultFill" },
"AR": { "fillKey": "defaultFill" },
"AL": { "fillKey": "defaultFill" }
}

return stateJSON
}